services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=[Database name]'
      - 'POSTGRES_PASSWORD=[Password]'
      - 'POSTGRES_USER=[Username]'
    ports:
      - '5432:5432'
