spring.application.name=BloggingApi

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.boot.sql.init=TRACE
logging.level.org.springframework.jdbc.datasource.init=TRACE
spring.sql.init.mode=always